# Generated by Django 3.1.4 on 2020-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perseptivTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='answers',
            name='email',
            field=models.EmailField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='answers',
            name='musician',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
